window.BOZORGMEHR_DATA = {
  translations: {
    fa: {
      dir: 'rtl', lang: 'fa', pageTitle: 'کافه رستوران بزرگمهر', brandName: 'کافه رستوران بزرگمهر', navHome: 'خانه', navMenus: 'منوها', navAbout: 'درباره ما', navBranches: 'شعب', navContact: 'تماس', switchLabel: 'English', navCall: 'تماس با ما', menuAction: 'مشاهده آیتم‌ها / دانلود PDF',
      heroEyebrow: 'کافه رستوران بزرگمهر', heroTitle: 'اصالت طعم،<br><em>در حدود نیم قرن تجربه</em>', heroText: 'سفره‌ای از طعم‌های اصیل، با کیفیتی که نسل‌ها به آن اعتماد کرده‌اند.', heroBadge: 'در حدود نیم قرن<br><span>میراث و مهمان‌نوازی</span>', heroCta: 'مشاهده منوها', callNow: 'تماس با ما',
      menuEyebrow: 'طعم‌های بزرگمهر', menuTitle: 'منوی رسمی ما', menuText: 'هر آنچه برای یک وعده به‌یادماندنی نیاز دارید؛ از برگر و پیتزا تا نوشیدنی‌های تازه.', download: 'دریافت منوی PDF', explore: 'مشاهده منو',
      aboutEyebrow: 'داستان ما', aboutTitle: 'طعم اصیل،<br><em>از سال ۱۳۶۰</em>', aboutText: 'از سال 1360<br>رستوران کنتاکی بزرگمهر با بیش از 4 دهه تجربه بخشی از خاطرات خوش مردم و مسافرین شهر مشهد است.<br>این مجموعه با ارائه انواع مختلف سوخاری، پیتزا، برگر، ساندویچ، پاستا و پیش غذا همه روزه در فضایی امن و آرام با رعایت موارد بهداشتی از مهمانان خود پذیرایی میکند.<br>مهمان عضوی از خانواده ی بزرگمهر است.', aboutQuote: 'زینب سادات میردیلمی، مدیر اجرایی مجموعه با بیش از ۱۰ سال تجربه حرفه‌ای در مدیریت غذا و نوشیدنی، باریستا و متخصص کیک و شیرینی، این مسیر را با دقت و مهمان‌نوازی ادامه می‌دهد.', managerTitle: 'مدیریت اجرایی', managerName: 'زینب سادات میردیلمی', managerText: 'مدیریت غذا و نوشیدنی، باریستا و متخصص کیک و شیرینی.', licenseTitle: 'اعتبار رسمی', licenseText: 'مجوزهای کسب‌وکار به نام احسان انحائی ناصری ثبت شده است.', licenseHolder: 'احسان انحائی ناصری', branchMeta1: 'مشهد / منتظری', branchMeta2: 'مشهد / بزرگمهر', branchPhone1: '۰۵۱۳۷۶۱۸۴۳۴', branchPhone2: '۰۵۱۳۷۶۳۸۵۵۵',
      branchesEyebrow: 'پیدایمان کنید', branchesTitle: 'شعب بزرگمهر', branch1: 'شعبه شهید منتظری', branch2: 'شعبه ملک‌آباد', address1: 'مشهد، بلوار شهید منتظری، بین خیابان شهید منتظری ۹ و ۱۱، ساختمان آستان قدس، پلاک ۱۲۶.۴، همکف.', address2: 'مشهد، بلوار ملک‌آباد، ابتدای بزرگمهر جنوبی، کنتاکی بزرگمهر.', route: 'مسیریابی', phoneLabel: 'رزرو و سفارش', galleryEyebrow: 'لحظه‌های خوشمزه', galleryTitle: 'بزرگمهر در قاب شما', contactEyebrow: 'با ما در ارتباط باشید', contactTitle: 'میز شما آماده است', contactText: 'برای سفارش، رزرو یا دریافت اطلاعات بیشتر با ما تماس بگیرید.', footerText: 'همراه مردم مشهد در حدود نیم قرن', rights: 'تمامی حقوق برای کافه رستوران بزرگمهر محفوظ است.', brandAlt: 'لوگوی کافه رستوران بزرگمهر', licenseAlt: 'مجوز رسمی کسب و کار', stampAlt: 'مهر رسمی مجموعه', menuAlt: 'تصویر دسته منو'
    },
    en: {
      dir: 'ltr', lang: 'en', pageTitle: 'Bozorgmehr kentucky Restaurant', brandName: 'Bozorgmehr kentucky Restaurant', navHome: 'Home', navMenus: 'Menus', navAbout: 'About Us', navBranches: 'Branches', navContact: 'Contact', switchLabel: 'فارسی', navCall: 'Call us', menuAction: 'View items / Download PDF',
      heroEyebrow: 'Bozorgmehr kentucky Restaurant', heroTitle: 'Authentic taste,<br><em>around half a century of experience</em>', heroText: 'A table of trusted flavors, prepared with care for generations of guests and travelers in Mashhad.', heroBadge: 'Around half a century<br><span>of heritage & hospitality</span>', heroCta: 'Explore menus', callNow: 'Call us',
      menuEyebrow: 'The Bozorgmehr selection', menuTitle: 'Our official menus', menuText: 'Everything for an unforgettable meal, from burgers and pizza to fresh drinks.', download: 'Download PDF menu', explore: 'Explore menu',
      aboutEyebrow: 'Our story', aboutTitle: 'Authentic taste,<br><em>since 1981</em>', aboutText: 'Since 1981<br>Bozorgmehr Kentucky Restaurant, with more than four decades of experience, is part of the fond memories of Mashhad residents and travelers.<br>Every day, we welcome guests in a safe, calm and hygienic setting with fried chicken, pizza, burgers, sandwiches, pasta and appetizers.<br>Every guest is a member of the Bozorgmehr family.', aboutQuote: 'Executive manager Zeinab Sadat Mirdeylami brings more than 10 years of professional food and beverage management, barista training, and pastry expertise to this heritage.', managerTitle: 'Executive management', managerName: 'Zeinab Sadat Mirdeylami', managerText: 'Food and beverage leadership, professional barista and pastry specialist.', licenseTitle: 'Officially trusted', licenseText: 'Business licenses are registered under Ehsan Anhaei Naseri.', licenseHolder: 'Ehsan Anhaei Naseri', branchMeta1: 'Mashhad / Montazeri', branchMeta2: 'Mashhad / Malek Abad', branchPhone1: '05137618434', branchPhone2: '05137638555',
      branchesEyebrow: 'Find us', branchesTitle: 'Bozorgmehr branches', branch1: 'Shahid Montazeri branch', branch2: 'Malek Abad branch', address1: 'Mashhad, Shahid Montazeri Blvd, between Montazeri 9 & 11, Astan Quds Bldg, No. 126.4.', address2: 'Mashhad, Malek Abad Blvd, southern entrance of Bozorgmehr, Kentucky Bozorgmehr.', route: 'Get directions', phoneLabel: 'Reservations & orders', galleryEyebrow: 'Good moments', galleryTitle: 'Bozorgmehr, through your lens', contactEyebrow: 'Stay in touch', contactTitle: 'Your table is ready', contactText: 'Call us for orders, reservations, or more information.', footerText: 'Serving Mashhad for around half a century', rights: 'All rights reserved to Bozorgmehr kentucky Restaurant.', brandAlt: 'Bozorgmehr kentucky Restaurant logo', licenseAlt: 'Official business license', stampAlt: 'Official establishment stamp', menuAlt: 'Menu category image'
    }
  },
  menus: [
    { id: 'burger', icon: '◉', image: './assets/images/burger.png', fa: 'برگر', en: 'Burgers', file: './assets/pdf/burger.pdf', descFa: 'برگرهای دست‌ساز با گوشت تازه و نان اختصاصی', descEn: 'Hand-crafted burgers with fresh beef and signature buns' },
    { id: 'pizza', icon: '◒', image: './assets/images/pizza.png', fa: 'پیتزا', en: 'Pizzas', file: './assets/pdf/pizza.pdf', descFa: 'خمیر تازه، پنیر کش‌دار و تاپینگ‌های سخاوتمندانه', descEn: 'Fresh dough, stretchy cheese and generous toppings' },
    { id: 'crispy', icon: '✦', image: './assets/images/crispy.png', fa: 'مرغ سوخاری', en: 'Crispy Chicken', file: './assets/pdf/crispy.pdf', descFa: 'سوخاری ترد و طلایی با ادویه مخصوص بزرگمهر', descEn: 'Golden crispy chicken with our signature seasoning' },
    { id: 'pasta', icon: '〰', image: './assets/images/pasta.png', fa: 'پاستا', en: 'Pastas', file: './assets/pdf/pasta.pdf', descFa: 'پاستاهای گرم و تازه با سس‌های محبوب', descEn: 'Fresh pasta with rich, comforting sauces' },
    { id: 'sandwiches', icon: '▰', image: './assets/images/sandwiches.png', fa: 'ساندویچ', en: 'Sandwiches', file: './assets/pdf/Sandwiches.pdf', descFa: 'ساندویچ‌های گرم و پرملات برای هر سلیقه', descEn: 'Loaded hot sandwiches for every craving' },
    { id: 'appetizer', icon: '✧', image: './assets/images/appetizer.png', fa: 'پیش‌غذا', en: 'Appetizers', file: './assets/pdf/appetizer.pdf', descFa: 'شروعی دلچسب برای یک تجربه کامل', descEn: 'The perfect opening to a complete experience' },
    { id: 'drink', icon: '◌', image: './assets/images/drink.png', fa: 'نوشیدنی', en: 'Beverages', file: './assets/pdf/drink.pdf', descFa: 'نوشیدنی‌های خنک و گرم برای تکمیل وعده', descEn: 'Refreshing and warm drinks to complete your meal' }
  ]
};
